# Site settings
title: My Personal Page - Adi Chris Bangun
email: adichrisbangun18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Adi Chris Bangun's personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrisbangun.github.io"
twitter_username: adichrisb
github_username:  chrisbangun

# Build settings
markdown: kramdown
