title: Hey Folks, it is ACB!
description: AI and Machine Learning Enthusiast.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Adi Chris Bangun
author-img: me.png
about-author: >-
  I am a Machine Learning Engineer with leading technology company in Indonesia. 
  Currently, I am interested in doing research on the generalization theory behind deep learning. 
  My long-term goal is to make deep neural network become more and more interpretable. 
twitter: adichrisb
facebook: adichrisbangun
github: chrisbangun
linkedin: adichrisbangun
email: adichrisbangun18@gmail.com

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
