# Site settings
name: Adi Chris Bangun
description: "Not really know who I am"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  chrisbangun
facebook_username: adichrisbangun
twitter_username: adichrisb
linked_in_username: adichrisbangun
stack_of_username: 2997327
email: adichrisbangun18@gmail.com


avatar: yes
avatar_img_path: "imgs/me.jpg"
# You mejamejamejamejemejcan link to your GitHub image. That way it will get updated 
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/Edinburgh.JPG"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
